.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2019 Partizand <partizand@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH usbhasp 1 SECTION "November  2 2019"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
usbhasp \- Research of usb hasp protection in Linux environment. Usb hasp emulator.
.SH SYNOPSIS
.B usbhasp
keyfile1.json keyfile2.json ...
.SH DESCRIPTION
Research of usb hasp protection in Linux environment. Usb hasp emulator.
It needs kernel modules from usb-vhci-hcd package for work.
As result creates virtual usb devices.
.SH OPTIONS
No options for this program
.SH SEE ALSO
.BR usbhaspd (1),
.br
